/**
 * build-tokens.mjs — Style Dictionary v4 multi-theme build.
 *
 * Produces, from the resolved token tree (ctx.paths.tokensDir):
 *   <outTokensCss>/base.css          :root  -> --raw-*, --p-*
 *   <outTokensCss>/theme-light.css   :root + [data-theme="light"] -> semantic vars
 *   <outTokensCss>/theme-dark.css    [data-theme="dark"]          -> semantic vars
 *   <outTokensCss>/theme-auto-dark.css  @media prefers-color-scheme
 *   <outTs>/base.tokens.ts           typed token list (raw + primitive)
 *   <outTs>/semantic.tokens.ts       typed token list (light semantics)
 *
 * Semantic vars use `outputReferences: true`, so they resolve to `var(--p-...)`.
 * Switching `data-theme` re-points the cascade with no rebuild.
 *
 * Run: npm run tokens:build  (or `jspr gen tokens`)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import StyleDictionary from 'style-dictionary';
import { loadConfig, materializeTokens } from './lib/config.mjs';
import { run as genRaw } from './gen-raw-from-tailwind.mjs';

StyleDictionary.registerTransform({
  name: 'base/name',
  type: 'name',
  transform: (token) => {
    const p = [...token.path];
    const tier = p.shift();
    if (tier === 'raw') return ['raw', ...p].join('-');
    if (tier === 'primitive') return ['p', ...p].join('-');
    return p.join('-'); // semantic: unprefixed for clean Tailwind mapping
  },
});

// Typed, flat token list consumed by the doc stories.
StyleDictionary.registerFormat({
  name: 'base/ts-tokens',
  format: ({ dictionary }) => {
    const all = dictionary.unfilteredAllTokens ?? dictionary.allTokens;
    const nameByPath = new Map(all.map((t) => [t.path.join('.'), t.name]));
    const refOf = (t) => {
      const v = t.original?.value;
      if (typeof v !== 'string') return null;
      const m = v.match(/^\{(.+)\}$/);
      if (!m) return null;
      const refName = nameByPath.get(m[1]);
      return refName ? `--${refName}` : null;
    };
    const rows = dictionary.allTokens.map((t) => ({
      name: t.name,
      cssVar: `--${t.name}`,
      type: t.type ?? null,
      path: t.path,
      value: typeof t.value === 'string' ? t.value : String(t.value ?? ''),
      ref: refOf(t),
    }));
    const CHUNK = 500;
    const chunks = [];
    for (let i = 0; i < rows.length; i += CHUNK) chunks.push(rows.slice(i, i + CHUNK));
    return (
      `// Generated by scripts/build-tokens.mjs — do not edit.\n` +
      `export type DesignToken = {\n` +
      `  name: string;\n  cssVar: string;\n  type: string | null;\n` +
      `  path: string[];\n  value: string;\n  ref: string | null;\n};\n` +
      // Emitted in typed chunks: one array literal of ~1.3k objects trips TS2590
      // ("union type too complex") during inference.
      chunks.map((c, i) => `const chunk${i}: DesignToken[] = ${JSON.stringify(c, null, 2)};\n`).join('') +
      `export const tokens: DesignToken[] = [${chunks.map((_, i) => `...chunk${i}`).join(', ')}];\n`
    );
  },
});

const TRANSFORMS = ['attribute/cti', 'base/name'];
const onlySemantic = (t) => t.path[0] === 'semantic';

async function build(config) {
  const sd = new StyleDictionary(config);
  await sd.buildAllPlatforms();
}

export async function run(ctx) {
  const { tokensDir, outTokensCss, outTs } = ctx.paths;
  const cssPath = outTokensCss.endsWith('/') ? outTokensCss : outTokensCss + '/';
  const tsPath = outTs.endsWith('/') ? outTs : outTs + '/';

  const BASE = [join(tokensDir, 'raw.json'), join(tokensDir, 'primitives.json')];
  const SHARED_SEMANTIC = [join(tokensDir, 'semantics', 'shared.json')];
  const THEMES = [
    { name: 'light', file: join(tokensDir, 'semantics', 'light.json'), default: true },
    { name: 'dark', file: join(tokensDir, 'semantics', 'dark.json'), default: false },
  ];

  // 1) Base: raw + primitive -> :root
  await build({
    source: BASE,
    platforms: {
      css: {
        transforms: TRANSFORMS,
        buildPath: cssPath,
        files: [
          {
            destination: 'base.css',
            format: 'css/variables',
            options: { selector: ':root', outputReferences: true },
          },
        ],
      },
      ts: {
        transforms: TRANSFORMS,
        buildPath: tsPath,
        files: [{ destination: 'base.tokens.ts', format: 'base/ts-tokens' }],
      },
    },
  });

  // 2) Per-theme: base (for reference resolution) + shared + that theme's semantics.
  for (const theme of THEMES) {
    await build({
      source: [...BASE, ...SHARED_SEMANTIC, theme.file],
      platforms: {
        css: {
          transforms: TRANSFORMS,
          buildPath: cssPath,
          files: [
            {
              destination: `theme-${theme.name}.css`,
              format: 'css/variables',
              filter: onlySemantic,
              options: {
                selector: theme.default
                  ? `:root, [data-theme="${theme.name}"]`
                  : `[data-theme="${theme.name}"]`,
                outputReferences: true,
              },
            },
          ],
        },
        ...(theme.default && {
          ts: {
            transforms: TRANSFORMS,
            buildPath: tsPath,
            files: [
              { destination: 'semantic.tokens.ts', format: 'base/ts-tokens', filter: onlySemantic },
            ],
          },
        }),
      },
    });
  }

  // Auto dark mode: re-emit dark semantics under prefers-color-scheme for an
  // unset data-theme; an explicit data-theme always wins (:not([data-theme])).
  const darkCss = readFileSync(join(outTokensCss, 'theme-dark.css'), 'utf8');
  const body = darkCss.slice(darkCss.indexOf('{') + 1, darkCss.lastIndexOf('}')).trimEnd();
  const auto =
    `/* Generated by scripts/build-tokens.mjs — do not edit.\n` +
    `   Unset data-theme follows the OS; an explicit data-theme overrides this. */\n` +
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {${body}\n  }\n}\n`;
  writeFileSync(join(outTokensCss, 'theme-auto-dark.css'), auto);

  console.log(`✓ tokens built → ${outTokensCss}, ${outTs}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const ctx = await loadConfig();
  await genRaw(ctx);
  materializeTokens(ctx);
  await run(ctx);
}
