/**
 * gen-theme.mjs — generate src/styles/theme.css (Tailwind v4).
 *
 * Goal: our tokens are the SINGLE source for every Tailwind utility, so a
 * sikat.config override (which regenerates the token tiers) flows to all consumer
 * utilities. We reset Tailwind's defaults and re-define each namespace from our
 * tokens.
 *
 *  - colors  → custom @utility per semantic token (themed): bg-/text-/border-/fg-
 *              (per-property, exact Figma role names, no flat collapse).
 *  - scales  → routed through the primitive vars (--p-*): spacing, radius,
 *              container, blur, font-size (+line-height), font-weight, font-family,
 *              letter-spacing, leading.
 *  - shadow  → composed back into a box-shadow from the decomposed parts.
 *  - breakpoints stay on Tailwind's defaults (CSS @media can't use var(); ours
 *    equal Tailwind's anyway).
 *
 * No numbered color ramp (primitives stay internal, like Figma).
 * Run: node scripts/gen-theme.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const color = JSON.parse(readFileSync(join(root, 'tokens/semantics/light.json'), 'utf8')).semantic.color;
const prim = JSON.parse(readFileSync(join(root, 'tokens/primitives.json'), 'utf8')).primitive;

/* ── colors: one @utility per semantic token, mapped to its CSS property ── */
const PROPS = {
  bg: ['background-color', 'bg'],
  text: ['color', 'text'],
  border: ['border-color', 'border'],
  fg: ['color', 'fg'], // foreground (drives currentColor icons)
};
let utils = '';
for (const [group, [cssProp, prefix]] of Object.entries(PROPS))
  for (const role of Object.keys(color[group] || {}))
    utils += `@utility ${prefix}-${role} {\n  ${cssProp}: var(--color-${group}-${role});\n}\n`;

// accent-color for native form controls (checkbox/radio) — themed via primary.
utils += `@utility accent-primary {\n  accent-color: var(--color-bg-primary);\n}\n`;

/* ── scales: route a Tailwind namespace through primitive vars ── */
const route = (twNs, primGroup) =>
  Object.keys(prim[primGroup]).map((k) => `  --${twNs}-${k}: var(--p-${primGroup}-${k});`).join('\n');

/* ── font-size: --text-<k> plus its paired --text-<k>--line-height ── */
const fontSize = Object.keys(prim['font-size'])
  .map((k) => {
    const lh = k in prim['line-height'] ? `\n  --text-${k}--line-height: var(--p-line-height-${k});` : '';
    return `  --text-${k}: var(--p-font-size-${k});${lh}`;
  })
  .join('\n');

/* ── shadow: compose the box-shadow from the decomposed parts (inner = inset) ── */
const shadow = Object.keys(prim.shadow)
  .map((size) => {
    const inset = size === 'inner' ? 'inset ' : '';
    const layers = Object.keys(prim.shadow[size])
      .map(
        (L) =>
          `${inset}var(--p-shadow-${size}-${L}-offset-x) var(--p-shadow-${size}-${L}-offset-y) ` +
          `var(--p-shadow-${size}-${L}-blur) var(--p-shadow-${size}-${L}-spread) var(--p-shadow-${size}-${L}-color)`,
      )
      .join(', ');
    return `  --shadow-${size}: ${layers};`;
  })
  .join('\n');

const css = `/**
 * theme.css — Tailwind v4 (GENERATED by scripts/gen-theme.mjs — do not edit).
 *
 * Our tokens are the single source for every Tailwind utility: defaults are reset
 * and each namespace re-defined from our tokens, so sikat.config overrides flow
 * through. Colors are themed @utility (bg-/text-/border-/fg-); scales route through
 * the primitive vars; shadow is composed from parts; breakpoints stay on Tailwind's
 * (CSS @media can't use var(), and they equal ours).
 * Exported as "@jasperlepardo/sikat-design-system/theme".
 */
@theme {
  /* reset Tailwind's defaults → token-only */
  --color-*: initial;
  --radius-*: initial;
  --shadow-*: initial;
  --inset-shadow-*: initial;
  --container-*: initial;
  --blur-*: initial;
  --text-*: initial;
  --font-*: initial;
  --font-weight-*: initial;
  --tracking-*: initial;
  --leading-*: initial;

  /* spacing — base unit; the multiplier drives p-/m-/gap-/w-/h-/size- utilities */
  --spacing: var(--p-spacing-1);

  /* radius → rounded-* */
${route('radius', 'radius')}

  /* container → max-w-* / @container */
${route('container', 'container')}

  /* blur → blur-* */
${route('blur', 'blur')}

  /* font-size → text-* (with paired line-height) */
${fontSize}

  /* font-weight → font-* */
${route('font-weight', 'font-weight')}

  /* font-family → font-sans (body) / font-heading / font-serif / font-mono */
  --font-sans: var(--p-font-family-body);
  --font-heading: var(--p-font-family-heading);
  --font-serif: var(--raw-font-family-serif);
  --font-mono: var(--raw-font-family-mono);

  /* letter-spacing → tracking-* */
${route('tracking', 'tracking')}

  /* line-height → leading-* */
${route('leading', 'leading')}

  /* shadow → shadow-* (composed from decomposed parts) */
${shadow}
}

/* ════ Semantic color utilities — per property, Figma-named, themed ════ */
${utils}`;

writeFileSync(join(root, 'src/styles/theme.css'), css);
console.log('✓ theme.css — defaults reset; scales+shadow routed through tokens; ' +
  `${utils.match(/@utility/g).length} color utilities`);
